# Generated by Django 5.0 on 2023-12-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_customuser_product_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
